AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PolicySynth-OPA – SCP pipeline (EventBridge -> Step Functions -> Lambdas)

Parameters:
  ArtifactBucket:
    Type: String
    Description: S3 bucket for generated policy bundles
  ArtifactPrefix:
    Type: String
    Default: generated/scp
  OpaLayerArn:
    Type: String
    Description: ARN of a Lambda Layer that provides /opt/bin/opa
  OrgId:
    Type: String
    Default: ""
    Description: (Optional) Constrain Organizations permissions to this Org ID

Globals:
  Function:
    Runtime: python3.11
    Timeout: 90
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        ARTIFACT_BUCKET: !Ref ArtifactBucket
        ARTIFACT_PREFIX: !Ref ArtifactPrefix
        OPA_BIN: /opt/bin/opa
    Layers:
      - !Ref OpaLayerArn

Resources:
  # ---------------- Lambdas ----------------
  ScpRetrieveFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.scp_pipeline.retrieve.lambda_handler
      CodeUri: src
      Policies:
        - Statement:
            - Sid: OrgsRead
              Effect: Allow
              Action:
                - organizations:DescribePolicy
                - organizations:ListPolicies
              Resource: "*"
              Condition:
                StringEqualsIfExists:
                  aws:ResourceOrgID: !Ref OrgId

  ScpGenerateFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.scp_pipeline.generate.lambda_handler
      CodeUri: src

  ScpValidateFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.scp_pipeline.validate.lambda_handler
      CodeUri: src

  ScpPublishFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.scp_pipeline.publish.lambda_handler
      CodeUri: src
      Policies:
        - Statement:
            - Sid: S3WriteArtifacts
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:ListBucket
                - s3:GetObject
                - s3:DeleteObject
                - s3:DeleteObjectVersion
              Resource:
                - !Sub arn:aws:s3:::${ArtifactBucket}
                - !Sub arn:aws:s3:::${ArtifactBucket}/*

  ScpDeleteArtifactsFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.scp_pipeline.delete_artifacts.lambda_handler
      CodeUri: src
      Policies:
        - Statement:
            - Sid: S3DeleteArtifacts
              Effect: Allow
              Action:
                - s3:ListBucket
                - s3:DeleteObject
                - s3:DeleteObjectVersion
                - s3:GetObject
              Resource:
                - !Sub arn:aws:s3:::${ArtifactBucket}
                - !Sub arn:aws:s3:::${ArtifactBucket}/*

  # ---------------- Step Functions ----------------
  ScpCreateUpdateStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: policiesynth-scp-createupdate
      Definition:
        Comment: "Create/Update SCP pipeline"
        StartAt: Retrieve
        States:
          Retrieve:
            Type: Task
            Resource: !GetAtt ScpRetrieveFn.Arn
            ResultPath: "$.retrieved"
            End: false
            Next: Generate
          Generate:
            Type: Task
            Resource: !GetAtt ScpGenerateFn.Arn
            InputPath: "$.retrieved.body"
            ResultPath: "$.generated"
            Next: Validate
          Validate:
            Type: Task
            Resource: !GetAtt ScpValidateFn.Arn
            InputPath: "$.generated.body"
            ResultPath: "$.validated"
            Next: Publish
          Publish:
            Type: Task
            Resource: !GetAtt ScpPublishFn.Arn
            InputPath: "$.validated.body"
            ResultPath: "$.published"
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ScpRetrieveFn
        - LambdaInvokePolicy:
            FunctionName: !Ref ScpGenerateFn
        - LambdaInvokePolicy:
            FunctionName: !Ref ScpValidateFn
        - LambdaInvokePolicy:
            FunctionName: !Ref ScpPublishFn

  ScpDeleteStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: policiesynth-scp-delete
      Definition:
        Comment: "Delete SCP artifacts pipeline"
        StartAt: DeleteArtifacts
        States:
          DeleteArtifacts:
            Type: Task
            Resource: !GetAtt ScpDeleteArtifactsFn.Arn
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ScpDeleteArtifactsFn

  # ---------------- EventBridge rules ----------------
  ScpCreateUpdateRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers pipeline on CreatePolicy/UpdatePolicy
      EventPattern:
        source: ["aws.organizations"]
        detail-type: ["AWS API Call via CloudTrail"]
        detail:
          eventSource: ["organizations.amazonaws.com"]
          eventName: ["CreatePolicy","UpdatePolicy"]
      State: ENABLED
      Targets:
        - Arn: !Ref ScpCreateUpdateStateMachine
          Id: "StartCreateUpdateSM"
          RoleArn: !GetAtt EventToSFNRole.Arn

  ScpDeleteRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers pipeline on DeletePolicy
      EventPattern:
        source: ["aws.organizations"]
        detail-type: ["AWS API Call via CloudTrail"]
        detail:
          eventSource: ["organizations.amazonaws.com"]
          eventName: ["DeletePolicy"]
      State: ENABLED
      Targets:
        - Arn: !Ref ScpDeleteStateMachine
          Id: "StartDeleteSM"
          RoleArn: !GetAtt EventToSFNRole.Arn

  EventToSFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: events.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: events-start-sfn
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource:
                  - !Ref ScpCreateUpdateStateMachine
                  - !Ref ScpDeleteStateMachine

Outputs:
  CreateUpdateSMArn:
    Value: !Ref ScpCreateUpdateStateMachine
  DeleteSMArn:
    Value: !Ref ScpDeleteStateMachine
  RetrieveFn:
    Value: !Ref ScpRetrieveFn
  PublishBucket:
    Value: !Ref ArtifactBucket
