AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PolicySynth-OPA – Event-driven SCP→OPA generation/validation/deploy

Parameters:
  ArtifactBucket:
    Type: String
    Description: S3 bucket for generated and distributed artifacts
  ArtifactPrefix:
    Type: String
    Default: generated/scp
  DistPrefix:
    Type: String
    Default: dist/scp
  OpaLayerArn:
    Type: String
    Description: ARN of a Lambda Layer that provides /opt/bin/opa (optional)
    Default: ""
  OrgId:
    Type: String
    Description: (Optional) Constrain Orgs permissions to this Organizations ID
    Default: ""

Globals:
  Function:
    Runtime: python3.11
    Timeout: 120
    MemorySize: 1024
    Tracing: Active
    Environment:
      Variables:
        ARTIFACT_BUCKET: !Ref ArtifactBucket
        ARTIFACT_PREFIX: !Ref ArtifactPrefix
        DIST_PREFIX: !Ref DistPrefix
        OPA_BIN: /opt/bin/opa
        WRITE_INTERMEDIATE: "true"

Resources:
  ScpPipelineFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: lambdas.scp_pipeline.app.lambda_handler
      Description: Retrieve → Generate → Validate → Deploy OPA bundles from SCPs
      Layers:
        - !If [HasOpaLayer, !Ref OpaLayerArn, !Ref "AWS::NoValue"]
      Policies:
        - Statement:
            - Sid: OrgsRead
              Effect: Allow
              Action:
                - organizations:ListPolicies
                - organizations:DescribePolicy
              Resource: "*"
              Condition:
                StringEqualsIfExists:
                  aws:ResourceOrgID: !Ref OrgId
            - Sid: S3RW
              Effect: Allow
              Action: [ "s3:PutObject", "s3:GetObject", "s3:DeleteObject" ]
              Resource:
                - !Sub arn:aws:s3:::${ArtifactBucket}/*
      Events:
        NightlySync:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
            Input: '{"stage":"retrieve_generate_validate_deploy"}'

  # Step Functions definition: 3 tasks over a single Lambda to keep packaging simple.
  ScpPipelineStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: policiesynth-scp-pipeline
      Definition:
        StartAt: RetrieveGenerate
        States:
          RetrieveGenerate:
            Type: Task
            Resource: !GetAtt ScpPipelineFn.Arn
            Parameters:
              stage: "retrieve_generate"
              # pass through the event payload if the rule supplied it
              "scp_s3.$": "$.scp_s3"
              "detail.$": "$.detail"
            ResultPath: "$.rg"
            Next: Validate
          Validate:
            Type: Task
            Resource: !GetAtt ScpPipelineFn.Arn
            Parameters:
              stage: "validate"
              "bundle_b64.$": "$.rg.body.bundle_b64"
            ResultPath: "$.val"
            Next: Deploy
          Deploy:
            Type: Task
            Resource: !GetAtt ScpPipelineFn.Arn
            Parameters:
              stage: "deploy"
              "bundle_b64.$": "$.rg.body.bundle_b64"
              "meta.$": "$.rg.body.meta"
            ResultPath: "$.deploy"
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ScpPipelineFn

  # EventBridge rule: send Orgs SCP CRUD events into the state machine
  ScpCrudRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers state machine when SCPs are created/updated/deleted
      EventPattern:
        source: [ "aws.organizations" ]
        detail-type: [ "AWS API Call via CloudTrail" ]
        detail:
          eventSource: [ "organizations.amazonaws.com" ]
          eventName: [ "CreatePolicy", "UpdatePolicy", "DeletePolicy" ]
      Targets:
        - Arn: !Ref ScpPipelineStateMachine
          Id: ScpPipelineSMTarget
          RoleArn: !GetAtt EventsToSfnRole.Arn

  EventsToSfnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: events.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: events-to-sfn
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !Ref ScpPipelineStateMachine

Conditions:
  HasOpaLayer: !Not [ !Equals [ !Ref OpaLayerArn, "" ] ]

Outputs:
  LambdaName:
    Value: !Ref ScpPipelineFn
  StateMachineArn:
    Value: !Ref ScpPipelineStateMachine
